services:
  odoo:
    image: odoo:19.0
    container_name: odoo19_service
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - .:/opt/odoo/project
    command: --config /opt/odoo/project/config/odoo.conf --dev=all

  db:
    image: postgres:16
    container_name: odoo19_db
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    
volumes:
  odoo-db-data: